### ISSUE TITLE
Adding A Note To A Person

### ISSUE THREAD

**Issue by conatus** [tapajos/highrise#30]
I am doing the following.

   person= Highrise::Person.find_all_across_pages(:params => {:name => 'David'}).first

   note = Highrise::Note.new

   note.body = 'Test.'
   note.subject_id = person.id

   note.save

And I get a 404 - how can I add a note? person.note.new doesn't work either.

(PS I'll do a example file and send a pull request if I find it out!)

**Comment by onurozgurozkan** [comment]
```ruby
person= Highrise::Person.find_all_across_pages(:params => {:name => 'David'}).first

note = Highrise::Note.new
note.body = 'Test.'
note.subject_id = person.id
note.subject_type = 'Party'
note.save
```

best regards
